fix:added workload profile to container env

diff --git a/.github/workflows/infrastructure.yml b/.github/workflows/infrastructure.yml
--- a/.github/workflows/infrastructure.yml
+++ b/.github/workflows/infrastructure.yml
@@ -101,22 +101,24 @@ jobs:
     #     rm -rf .terraform
     #     rm -f .terraform.lock.hcl
     #     rm -f terraform.tfstate*
-    - name: Clean Existing Container Resources
-      run: |
-        echo "Deleting Container Apps..."
-        az containerapp delete --name "nohdevjun2025frontend" \
-        --resource-group "nohdevjun2025" --yes || echo "Frontend not found"
-        az containerapp delete --name "nohdevjun2025server" --resource-group \
-        "nohdevjun2025" --yes || echo "Server not found"
-        az containerapp delete --name "nohdevjun2025keycloak" \
-        --resource-group "nohdevjun2025" --yes || echo "Keycloak not found"
 
-        echo "Waiting for Container Apps to be deleted..."
-        sleep 30
+    
+    # - name: Clean Existing Container Resources
+    #   run: |
+    #     echo "Deleting Container Apps..."
+    #     az containerapp delete --name "nohdevjun2025frontend" \
+    #     --resource-group "nohdevjun2025" --yes || echo "Frontend not found"
+    #     az containerapp delete --name "nohdevjun2025server" --resource-group \
+    #     "nohdevjun2025" --yes || echo "Server not found"
+    #     az containerapp delete --name "nohdevjun2025keycloak" \
+    #     --resource-group "nohdevjun2025" --yes || echo "Keycloak not found"
 
-        echo "Deleting Container App Environment..."
-        az containerapp env delete --name "nohdevjun2025containerenv" \
-        --resource-group "nohdevjun2025" --yes || echo "Environment not found"
+    #     echo "Waiting for Container Apps to be deleted..."
+    #     sleep 30
+
+    #     echo "Deleting Container App Environment..."
+    #     az containerapp env delete --name "nohdevjun2025containerenv" \
+    #     --resource-group "nohdevjun2025" --yes || echo "Environment not found"
     
     - name: Terraform Init
       if: steps.changes.outputs.HAS_INFRA_CHANGES == 'true' || github.event_name == 'workflow_dispatch'
